회원가입 기능 구현
boostcamp-2020/IssueTracker-40 pull request #74
Opened 2020-11-08 13:59 UTC by wooojini

## 📕 제목

회원가입 기능 구현
관련 이슈 #69 

## 📗 작업 내용

> 구현 내용 및 작업 했던 내역

- [x] 회원가입 API 작성
  - POST /signup 형태로 회원가입 form데이터를 처리하도록 구현하였습니다.
  - Request 데이터
 ```
{
  email: "",
  name: "",
  password: ""
}
 ```
- [x] 회원가입 로직 작성
  - 회원가입 요청시 body 데이터를 통해 전송된 회원가입 form 데이터 유효성 검사를 실시합니다.
    - 유효성 검사는 form데이터가 모델에 정의된 데이터 타입과 일치하는지를 검사합니다.
    - class-validator를 활용하여 유효성 검사 실시 후, 검사결과에 따라 다음 미들웨어에서 처리할 수 있도록 request객체에 user 정보를 추가하고 다음 미들웨어로 넘어가거나 400 응답코드를 보냅니다.
  - 유효성 검사 통과 후, 기존에 회원가입된 회원정보가 존재하는지 검사를 실시합니다.
    - email, name 모두 unique 해야하므로 두 필드 모두 DB에 존재하는지 검사합니다.
    - 이미 회원가입된 정보가 존재하는지 여부에 따라 다음 미들웨어로 넘어가거나 400번 응답코드를 보냅니다.
  - 위 검사 절차가 모두 통과된 경우, DB에 user 정보를 추가하여 회원가입을 합니다.

## 📘 PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 기능 구현을 위주로 빠르게 구현하여 PR을 보냈습니다. 놓친 부분이나 추가했으면 하는 부분은 거침없이 리뷰 남겨주세용 :-)
- 프로필 이미지는 이미지서버도 아직 구현되어 있지 않고, 별도의 이미지를 등록하는 폼 구현이 들어갈 것 같아서 일단은 하드코딩으로 크롱이미지를 자동으로 추가하도록 했습니다 :-)
- 에러객체에 메세지를 삽입할 수 있으면 좋겠다는 생각이 들었습니다! 예를들면 회원가입 실패시 이메일이 문제가 있는지, 패스워드가 문제가 있는지 클라이언트에게 메세지를 보낼 수 있으면 클라이언트에서 적절한 처리를 해줄 수 있을 것 같습니다!
-

2020-11-08 17:12 UTC, jinhyukoo commented on backend/src/controller/signup-controller.js
> +    const error = await validate(newUser);
이 부분은 email, name, password의 유효성을 검사하는 부분인 것 같은데 원리가 궁금하네요! validate(newUser)가 어떤식으로 동작을 하는건지 여쭤봐도 될까요?

2020-11-08 17:12 UTC, jinhyukoo commented on backend/src/service/user-service.js
> +
GitHub 로그인과 일반 회원가입 처리에 대해 두 종류의 함수로 나눈것 같은데 password의 기본 설정을 null이나 undefined로 해놓고 두 함수를 합칠 수는 없을까요? 중복되는 부분인 것 같아 리팩토링 할 수 있으면 좋을 것 같아서 여쭤봅니다!

2020-11-08 17:19 UTC, wooojini commented on backend/src/controller/signup-controller.js
> +    const error = await validate(newUser);
validate 함수의 인자로 class-validater의 데코레이터로 검사할 프로퍼티 항목을 지정해준 클래스의 인스턴스를 넣어주면, 검사에 실패한 프로퍼티에 대한 error를 배열에 담아 반환해줍니다. 해당 error 배열을 통해 어떤 항목이 유효성 검사에 실패했는지 또는 배열의 길이 값을 통해 유효성 검사를 통과했는지 여부를 알 수 있습니다 :-)

2020-11-08 17:56 UTC, jinhyukoo commented on backend/src/controller/signup-controller.js
> +    const error = await validate(newUser);
각각의 데코레이터가 어디에 설정되어 있는지 찾질 못해서 질문드렸습니다...ㅠㅠㅠ 아직 제가 이해가 많이 부족한 것 같네융...

2020-11-08 17:56 UTC, wooojini commented on backend/src/service/user-service.js
> +
@jinhyukoo 거침없는 리뷰 좋습니다! 지금보니 해당 함수를 왜 나눴는지 모르겠습니다... createUser라는 하나의 메소드로 수정하고, UserService의 다른 메소드에서 회원을 생성하는 부분을 해당 메소드를 사용하여 재사용할 수 있도록 코드 수정했습니다 :-)

2020-11-08 17:58 UTC, wooojini commented on backend/src/controller/signup-controller.js
> +    const error = await validate(newUser);
@jinhyukoo 데코레이터는 User 모델에 설정되어 있습니다!
@isEmail과 같이 데코레이터 설정된 부분을 validate가 참고하여 인스턴스의 프로퍼티를 검사하는 방식인 것 같습니다 :-)
```
@Entity({ name: "user" })
class User {
    @PrimaryGeneratedColumn("increment", { type: "int" })
    id;

    @Column({ name: "email", type: "varchar", unique: true })
    @IsEmail()
    email;

    @Column({ name: "name", type: "varchar", unique: true, charset: "utf-8" })
    @IsString()
    @Length(4, 20)
    name;

    @Column({ name: "password", type: "varchar", nullable: true })
    @IsOptional()
    @IsString()
    password;
    ....
```

2020-11-08 18:24 UTC, youngxpepp requested changes
저는 리뷰가 조금 많네요ㅠㅠㅠㅠ
천천히 읽어보시고 피드백 부탁 드려요! 정말 고생하셨습니다👍

2020-11-08 18:24 UTC, youngxpepp commented on backend/src/controller/signup-controller.js
> +    const userService = new UserService();
```suggestion
    const userService = UserService.getInstance();
```
UserService를 싱글톤으로 가져가면 매번 UserService 인스턴스를 만들지 않아도 될 것 같아요!

2020-11-08 18:24 UTC, youngxpepp commented on backend/src/service/user-service.js
>  class UserService {
```suggestion
class UserService {
    static instance = null;
    static getInstance() {
        if (UserService.instance === null) {
            UserService.instance = new UserService();
        }
        return UserService.instance;
    }
```
싱글톤 패턴은 어떨까요? babel을 써서 static property가 지원됩니다!

2020-11-08 18:24 UTC, youngxpepp commented on backend/src/common/lib/crypto.js
> +const bcrypt = require("bcrypt");
module 방식으로 하는건 어떨까요? 내부적으로 어떤 차이가 있는지는 모르겠지만, 다른 파일들과 같이 es6 문법을 사용하면 좋을 것 같다는 생각이 듭니다! 😃

2020-11-08 18:24 UTC, youngxpepp commented on backend/src/common/lib/crypto.js
> +    const hash = (data, salt) => bcrypt.hashSync(data, salt);
bcrypt의 해쉬연산은 라운드가 거듭될 때마다 엄청난 CPU 연산을 하게 돼요! https://d2.naver.com/helloworld/318732
Nodejs의 이벤트루프는 싱글 스레드이기 때문에 bcrypt의 연산이 다른 요청에 큰 방해가 될 수 있다고 생각합니다ㅎㅎ 비동기 처리로 수정하는 것을 추천드려요. NPM에 나온 bcrypt 문서를 첨부합니다. https://www.npmjs.com/package/bcrypt#why-is-async-mode-recommended-over-sync-mode

2020-11-08 18:24 UTC, youngxpepp commented on backend/src/router/signup.js
> +router.post("/", signupController.validateSignupParam, signupController.checkUserSignedUp, signupController.signup);
여러 개의 미들웨어로 분리한 이유가 있을까용? 🧐
하나의 트랜잭션으로 묶어서 디비 커넥션을 계속 쥐고 있는 것이 좀 더 효율적이라고 생각합니다ㅎㅎ
우진님 방식처럼 하면 서비스 로직을 논리적으로 분리는 할 수 있지만 디비 커넥션을 여러번 사용하고 반납하고를 반복하게 될 것 같아요.

2020-11-08 18:39 UTC, wooojini commented on backend/src/controller/signup-controller.js
> +    const userService = new UserService();
@youngxpepp 함수형으로 구현하다보니 매번 서비스 인스턴스 생성에 대해 고민중이었는데 싱글톤 방식이 해결책이 될 수 있겠군요!
제안해주신 코드 잘 참고하였습니다 :-) 평소 싱글톤 객체를 만들때 모듈을 이용하고 있습니다. Node.js로 모듈파일 내에서 인스턴스 생성 후 내보내면 캐시가 적용되어 해당 모듈을 참조하는 곳에서는 같은 인스턴스를 참조하여 싱글톤을 적용할 수 있게 되는데 제안해주신 코드처럼 패턴을 직접 구현하는 것과 차이점이 존재할까요??

2020-11-08 18:43 UTC, wooojini commented on backend/src/common/lib/crypto.js
> +const bcrypt = require("bcrypt");
앗! 모듈방식을 쓰지 않고 있었군요! 세심한 리뷰 좋습니다!

2020-11-08 18:47 UTC, wooojini commented on backend/src/common/lib/crypto.js
> +    const hash = (data, salt) => bcrypt.hashSync(data, salt);
@youngxpepp 건홍님 리뷰를 받다보면 정말 서버관점에서 많은 부분을 생각하고 계시는게 느껴집니다! 해쉬연산에 대한 cpu 리소스 관점에서의 접근은 생각지도 못했습니다. 올려주신 글들 잘 참고해서 수정해보겠습니다 :-)

2020-11-08 18:51 UTC, wooojini commented on backend/src/router/signup.js
> +router.post("/", signupController.validateSignupParam, signupController.checkUserSignedUp, signupController.signup);
@youngxpepp 맞습니다! 구현해놓고 보니 하나의 트랜잭션으로 묶어줄 수 있지않을까하는 생각이 들어서 공식문서를 참조하고 있었습니다! 역시 놓치지않고 리뷰 주시는군요 :-)

2020-11-09 02:07 UTC, Do-ho approved these changes
다른 분들이 리뷰 잘해주셔서 수정하시고 반영해주시면 될 것 같습니다! Approve 하겠습니다~

2020-11-09 02:07 UTC, Do-ho commented on backend/src/controller/signup-controller.js
> +    res.status(200).send("");
이 부분에 데이터를 넣어보면 어떨까요?
```
res.status(200).send("Ok");
```

2020-11-09 03:11 UTC, youngxpepp commented on backend/src/controller/signup-controller.js
> +    const userService = new UserService();
차이가 없을 듯 해요ㅎㅎㅎ 클래스로 선언된 만큼 최대한 객체지향적으로 설계하려고 했었는데, 우진님 방식이 더 간단하다고 생각이 듭니다!

2020-11-09 06:23 UTC, jinhyukoo approved these changes

2020-11-09 06:58 UTC, wooojini commented on backend/src/controller/signup-controller.js
> +    const userService = new UserService();
@youngxpepp 그렇군요! 모듈 방식을 이용하면 코드는 간결해지지만,  Class에 패턴을 구현하면, 확실히 해당 서비스를 참조해서 개발하시는 다른 분들이 싱글톤 패턴을 구현했는지 명확하게 이해할 것 같습니다 :-)

2020-11-09 06:58 UTC, wooojini commented on backend/src/service/user-service.js
>  class UserService {
싱글톤 방식으로 수정했습니다 :-)

2020-11-09 08:28 UTC, youngxpepp approved these changes
고생하셨습니다👍 덕분에 저도 자료를 많이 찾아보는 계기가 되었습니다!

2020-11-09 09:43 UTC, wooojini commented on backend/src/controller/signup-controller.js
> +    res.status(200).send("");
@Do-ho  데이터 추가했습니다!!! 메세지 형식을 지정해봐도 좋을 것 같네요 :-)

2020-11-09 09:44 UTC, merged